import { useState } from 'react';
import './TermsModal.css';

export const TERMS_KEY = 'llm_council_terms_accepted_v1';
export const CONTACT_EMAIL = 'llmcouncilsupport@africaisoft.africa';

export function hasAcceptedTerms() {
  try {
    return localStorage.getItem(TERMS_KEY) === 'true';
  } catch {
    return false;
  }
}

export default function TermsModal({ onAccept }) {
  const [checked, setChecked] = useState(false);

  const accept = () => {
    if (!checked) return;
    try {
      localStorage.setItem(TERMS_KEY, 'true');
    } catch { /* noop */ }
    onAccept();
  };

  return (
    <div className="terms-overlay" data-testid="terms-modal">
      <div className="terms-modal" role="dialog" aria-modal="true" aria-labelledby="terms-title">
        <header className="terms-header">
          <span className="terms-logo">⚖︎</span>
          <h2 id="terms-title">Terms &amp; Conditions</h2>
        </header>

        <div className="terms-body">
          <section>
            <h3>1. Terms of Use</h3>
            <p>
              Welcome to <strong>LLM Council</strong>. By accessing or using this platform, you agree to
              use it lawfully and responsibly. The platform orchestrates multiple large language models
              to produce a deliberated answer. Responses are generated by third-party AI models and may
              contain inaccuracies; they are provided for informational purposes only and do not constitute
              professional, legal, medical, or financial advice. You remain solely responsible for how you
              use any output.
            </p>
          </section>

          <section>
            <h3>2. Acceptable Use</h3>
            <p>
              You agree not to submit unlawful, harmful, or abusive content, not to attempt to disrupt the
              service, and not to use the platform to infringe the rights of others. Credits consumed to run
              a council request are governed by the pricing displayed in your account.
            </p>
          </section>

          <section>
            <h3>3. Data Protection &amp; Privacy</h3>
            <p>
              We process the minimum data required to operate the service: your account identity (email and
              display name) and the conversations you create. Prompts and documents you submit are sent to the
              configured AI providers solely to generate responses. We do not sell your personal data. Data is
              retained while your account is active and may be deleted upon request. By continuing, you consent
              to this processing in accordance with applicable data protection laws.
            </p>
          </section>

          <section>
            <h3>4. Contact</h3>
            <p>
              For any question regarding these terms or your data, contact us at{' '}
              <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
            </p>
          </section>
        </div>

        <label className="terms-checkbox">
          <input
            type="checkbox"
            checked={checked}
            onChange={(e) => setChecked(e.target.checked)}
            data-testid="terms-accept-checkbox"
          />
          <span>I have read and accept the Terms of Use and the Data Protection conditions.</span>
        </label>

        <div className="terms-actions">
          <button
            className="terms-accept-btn"
            disabled={!checked}
            onClick={accept}
            data-testid="terms-accept-btn"
          >
            Accept &amp; Continue
          </button>
        </div>
      </div>
    </div>
  );
}
